### ISSUE TITLE
Import problem with opencv 4.6

### ISSUE THREAD

**Issue by fjrefluxx** [jonashoechst/facecropper#5]
Just running  `pip install .` install the newest version of opencv-python (currently 4.6.0.66), resulting in an import error:

`ImportError: Bindings generation error. Submodule name should always start with a parent module name. Parent name: cv2.cv2. Submodule name: cv2`

Defining an older version in requirements.txt fixes this error, e.g., `opencv-python == 4.5.5.64`.

**Comment by jonashoechst** [comment]
This seems to be an issue of recent opencv versions, as described here: https://github.com/opencv/opencv-python/issues/676
